# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='ContentTag',
            new_name='Tag',
        ),
        migrations.CreateModel(
            name='NameContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            bases=('content.content',),
        ),
    ]
