# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200201_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='content.Content')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='content.Tag')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'control'),
            },
        ),
    ]
