# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contenttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='strict',
            field=models.BooleanField(default=False, help_text='if True then the Tag will _always_ require strict adherence in generation (if it is requested, it must apply)'),
        ),
    ]
